export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";
export const FILTER_TASK = "FILTER_TASK";
export const TOGGLE_COMPLETED_TASK = "TOGGLE_COMPLETED_TASK";
